name: Publish Site
on:
  workflow_dispatch:
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create SSH key
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.LICENSE_SERVER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.LICENSE_SERVER_SSH_HOST }}" > ~/.ssh/known_hosts
        mkdir build/
        cp README.md build/
    - name: Deploy with rsync
      shell: bash
      run: |
        rsync -rav --delete build/ ${{ secrets.LICENSE_SERVER_HOST }}@${{ secrets.LICENSE_SERVER_USERNAME }}:/home/github/www/
